name: 🌸 Публикация новостей Noob Club

on:
  schedule:
    - cron: '*/15 * * * *'  # Запуск каждые 15 минут
  workflow_dispatch:

jobs:
  post_news:
    runs-on: ubuntu-latest

    steps:
      - name: 📆 Клонируем репозиторий
        uses: actions/checkout@v4

      - name: 🌺 Восстановление кэша seen_links.txt
        uses: actions/cache@v4
        with:
          key: seen-links-${{ runner.os }}
          restore-keys: seen-links-
          path: seen_links.txt

      - name: 🐍 Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: ✨ Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🌟 Запуск скрипта
        run: python main.py

      - name: 📥 Сохраняем кэш seen_links.txt
        if: always()
        uses: actions/cache/save@v4
        with:
          key: seen-links-${{ runner.os }}-${{ github.run_id }}
          path: seen_links.txt
